---
title: "DynaSym Educational Materials"
bibliography: references/README.bib
date: "`r Sys.Date()`"
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

**Note that this repository is active and content will change over time.**

## Summary

This repository hosts educational materials for the research unit [DynaSym](https://www.dynasym.uni-konstanz.de/). DynaSym is funded by the German Research Foundation, DFG, see also information on DynaSym [there](https://gepris.dfg.de/gepris/projekt/528028597?language=en).

DynaSym aims at investigating the dynamics of interactions in symbiotic partners. In classical (theoretical) community ecology, the direct interactions are set as static over time; however, the strength and also the sign of such an interaction may change [@HollandEtAl2002PopulationDynamicsMutualism; @BecksEtAl2025EmergentFeedbackSymbiosis].

Our research unit aims at understanding the dynamics of species interactions, especially the density dependence **functional response**, and the consequences for population dynamics and species coexistence. To do so, we want to connect experimental approaches and use the insights to revise existing mathematical models. To assure seamless communication and exchange of research within our group, we want to provide all necessary knowledge here, e.g., how to fit functional responses to data to estimate the strength of species interactions [@RosenbaumRall2018FittingFunctionalResponses].

This educational repository will cover topics from, e.g., computational biology, open science, population ecology, statistics, or theoretical ecology, just to name a few. We will update the contents later.

**Stay tuned for updates!**


## License

Most of the educational materials will be published under the [**Creative Commons BY 4.0**](https://creativecommons.org/licenses/by/4.0/) license. The underlying code will be licensed for instance under the [**GNU General Public License 3**](https://www.gnu.org/licenses/gpl-3.0.html) or other software compatible licenses (see code files and chunks for specific licenses).

## How to cite this repository

We aim at publishing parts of the content like presentations or other written materials on [Zenodo](https://zenodo.org/) that will allow you to cite us properly. We will update this section upon a Zenodo release. If you want to refer to this repository, you can use (for now):

Rall, B.C. (2025): DynaSym Educational Materials. https://github.com/b-c-r/DynaSymEducation


## Author(s)

-   Björn C. Rall ([0000-0002-3191-8389](https://orcid.org/0000-0002-3191-8389))
    -   [bjoern.rall@uni-konstanz.de](mailto:bjoern.rall@uni-konstanz.de)
    -   Aquatic Ecology and Evolution Group, Limnological Institute, University of Konstanz, Mainaustraße 252, 78464 Konstanz/Egg, Germany

## Links of Interest

-   DynaSym homepage: https://www.dynasym.uni-konstanz.de/
-   DynaSym DFG homepage: https://gepris.dfg.de/gepris/projekt/528028597?language=en

## Funding Information

-   Björn C. Rall gratefully acknowledges the funding by the [**German Science Foundation (DFG) to the Research Unit DynaSym (FOR 5726)**](https://gepris.dfg.de/gepris/projekt/528028597).

## References
